### PR TITLE
update shmig

### PR DESCRIPTION
**Pull request by agonen**

### CODE REVIEW

**Comment by agonen** [comment]
add verbose as option to shmig .I've implemented for Postgresql, making debug easier.

**Comment by mbucc** [comment]
@agonen can you change branch shmig branch from master to verbose on this pull request?

I want to add mysql and sqlite options and test on a branch before merging into master.

**Comment by mbucc** [comment]
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by agonen** [comment]
@mbucc  I will gladly do , but can you exaplain what do you mean change branch ? do you want me to create a new branch ?

**Comment by mbucc** [comment]
@agonen Great.  You don't need to create a new branch.  Just need to edit your open pull request and change the branch from base:master to base:verbose.   This shows you how: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

Thanks.

**Comment by agonen** [comment]
Done

**Pull request merged**
