### PR TITLE
Implemented config option for recursive migrations (refs mbucc/shmig#43)

### PR DESCRIPTION
**Pull request by kael-shipman**
Ok, I've got an initial implementation of this, though I wasn't able to figure out a good posix-find equivalent to gnu-find's `maxdepth` parameter. ([This](https://unix.stackexchange.com/a/330372) looked promising, though I didn't have enough time to figure out how to make it work for our purposes.)

I'm submitting this PR now because it solves the problem posed in issue #43 without _regressing;_ that is, since the code _already_ uses gnu find's `maxdepth` parameter, we don't lose any portability with this implementation, we just don't _gain_ any.

@mbucc , would you be interested in trying to implement posix compatibility on this?

### CODE REVIEW

**Comment by mbucc** [comment]
Excellent, thank you.

I was thinking of simply removing the -(min|max)depth args completely.  Then there is no need for a new config option.

Any objection?

I think there is a small probability of breaking existing setups ...

**Comment by kael-shipman** [comment]
No problema from me :). Your call!

**Comment by mbucc** [comment]
I merged locally, so I'll close this PR.

Before pushing to master, I want to make sure I ensure the order of files returned by a find.

This has opened up a kind of interesting corner case: it looks like the order of files returned by find is not guaranteed.  Quoting from https://serverfault.com/a/181815:

> find will be traversing the directory tree in the order items are stored within the directory entries. This will (mostly) be consistent from run to run, on the same machine and will essentially be "file/directory creation order" if there have been no deletes.
>
> However, some file systems will re-order directory entries as part of compaction operations or when the size of the entry needs to be expanded, so there's always a small chance the "raw" order will change over time. If you want a consistent order, feed the output through an extra sorting stage.

Also note that he is talking about ordering of entries within each directory; I'm not sure what happens about ordering across different directories.

That also means the file name itself makes no difference to find as far as ordering.  We could store use the sha1 of the file contents as the filename and find would still return the same order.  `find $dir -type f -name '*.sql' | xargs ls -Ur` would guarantee the order, but xargs has a limit (which varies by system?) on the total number of input files it will handle.  It would really suck if your db migration tool stopped working when you went over some magic number of migrations.

**Comment by kael-shipman** [comment]
Cool! Looking through the source, it doesn't appear to me that it's a problem that find doesn't return ordered results. (Where it matters, it looks like you always pipe it to `sort` anyway, which makes sense.) Maybe I'm not understanding the problem you've recognized?

**Comment by srghma** [comment]
@kael-shipman tnx, will check it

**Pull request closed without merging**
